# From https://orchid00.github.io/actions_sandbox/websites-using-pkgdown-bookdown-and-blogdown.html#deploy-bookdown
on:
  push:
     branches:
       - main

name: renderbook

jobs:
  bookdown:
    name: Render & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Download latest Pandoc
        run: curl -sL https://api.github.com/repos/jgm/pandoc/releases/latest | jq -r '.assets[].browser_download_url' | grep "amd64.deb$" | wget -qi -
      - name: Install Pandoc
        run: sudo dpkg -i *amd64.deb
      - name: Create _site directory
        run: mkdir _site
      - name: Render HTML
        run: pandoc --citeproc -o _site/index.html thesis.md
      - name: Deploy to GitHub Pages
        uses: Cecilapp/GitHub-Pages-deploy@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          email: email@jacobhall.net
